Universal init script

diff --git a/supervisord b/supervisord
--- a/supervisord
+++ b/supervisord
@@ -26,12 +26,56 @@
 
 if [ -f /etc/redhat-release ]; then
 	. /etc/rc.d/init.d/functions
+
+	status_of_proc()
+	{
+		status "$2"
+	}
+
+	log_daemon_msg()
+	{
+		echo -n "$@ "
+	}
+
+	log_end_msg()
+	{
+		case "$1" in
+			0 )
+				echo_success
+				echo
+				;;
+			1 )
+				echo_failure
+				echo
+				;;
+		esac
+	}
+
+	log_warning_msg()
+	{
+		log_daemon_msg "$@"
+		echo_warning
+		echo
+	}
+
+	log_failure_msg()
+	{
+		log_daemon_msg "$@"
+		echo_failure
+		echo
+	}
+
+	log_success_msg()
+	{
+		log_daemon_msg "$@"
+		echo_success
+		echo
+	}
 elif [ -f /etc/debian-release ]; then
 	# Load the VERBOSE setting and other rcS variables
 	. /lib/init/vars.sh
 
 	# Define LSB log_* functions.
-	# Depend on lsb-base (>= 3.0-6) to ensure that this file is present
 	. /lib/lsb/init-functions
 fi
 
@@ -59,76 +103,45 @@ if [ -f /etc/default/supervisor ] ; then
 fi
 
 
-running_pid()
-{
-	# Check if a given process pid's cmdline matches a given name
-	pid=$1
-	name=$2
-	[ -z "$pid" ] && return 1
-	[ ! -d /proc/$pid ] &&  return 1
-	(cat /proc/$pid/cmdline | tr "\000" "\n"|grep -q $name) || return 1
-	return 0
-}
-
 running()
 {
-# Check if the process is running looking at /proc
-# (works for all users)
-
-	# No pidfile, probably no daemon present
 	[ ! -f "$PIDFILE" ] && return 1
-	# Obtain the pid and check it against the binary name
-	pid=`cat $PIDFILE`
-	running_pid $pid $DAEMON || return 1
-	return 0
-}
 
-status()
-{
-	case "$1" in
-		0 )
-			echo "Success"
-			;;
-		1 )
-			echo "\033[31mError\033[0m"
-			;;
-		2 )
-			echo "Error! $DESC is currently running!"
-			;;
-		3 )
-			echo "Error! $DESC is currently not running!"
-			;;
-		4 )
-			echo "Cannot kill $DESC (pid=$pid)!"
-			;;
-	esac
+	pid=`cat $PIDFILE`
+	proc=$(pidofproc $DAEMON)
+	[ $proc -eq $pid ] || return 1
+	return 0
 }
 
 do_start()
 {
-	if running; then
-		return 2
-	else
-		echo -n "Starting $DESC: "
+	if ! running; then
+		log_daemon_msg "Starting $DESC" "$NAME"
 		$DAEMON --pidfile $PIDFILE $DAEMON_OPTS > /dev/null
 		test -f $PIDFILE || sleep 1
-		return $(running)
+		if running; then
+			log_end_msg 0
+		else
+			log_end_msg 1
+		fi
+	else
+		log_warning_msg "$DESC is currently running!"
 	fi
 }
 
 do_stop()
 {
 	if running; then
-		echo -n "Stopping $DESC: "
+		log_daemon_msg "Stopping $DESC " "$NAME"
 		$SUPERVISORCTL $DAEMON_OPTS shutdown > /dev/null
-		test -f $PIDFILE || sleep 1
+		test -f $PIDFILE || [ -n "$DODTIME" ] && sleep "$DODTIME"s
 		if running; then
-			return 1
+			log_end_msg 1
 		else
-			return 0
+			log_end_msg 0
 		fi
 	else
-		return 3
+		log_warning_msg "$DESC is currently not running!"
 	fi
 }
 
@@ -142,74 +155,81 @@ do_force_stop()
 			kill -9 $pid
 			[ -n "$DODTIME" ] && sleep "$DODTIME"s
 			if running; then
-				return 4
+			log_failure_msg "Cannot kill $DESC (pid=$pid)!"
+			log_end_msg 1
 			else
 				rm -f $PIDFILE
-				return 0
+				log_end_msg 0
 			fi
 		else
 			rm -f $PIDFILE
-			return 0
+			log_end_msg 0
 		fi
 	else
-		return 3
+		log_warning_msg "$DESC is currently not running!"
 	fi
 }
 
 do_reload()
 {
 	if running; then
-		echo -n "Reloading $DESC: "
+		log_daemon_msg "Reloading $DESC " "$NAME"
 		$SUPERVISORCTL $DAEMON_OPTS update > /dev/null
-		return $(running)
+		if running; then
+			log_end_msg 0
+		else
+			log_end_msg 1
+		fi
 	else
-		return 3
+		log_warning_msg "$DESC is currently not running!"
 	fi
 }
 
 do_restart()
 {
 	if running; then
-		echo -n "Restarting $DESC: "
+		log_daemon_msg "Restarting $DESC: "
 		$SUPERVISORCTL $DAEMON_OPTS reload > /dev/null
 		test -f $PIDFILE || sleep 1
-		return $(running)
+		if running; then
+			log_end_msg 0
+		else
+			log_end_msg 1
+		fi
 	else
-		return 3
+		log_warning_msg "$DESC is currently not running!"
 	fi
+}
+
+do_status()
+{
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 }
 
 case "$1" in
 	start )
 		do_start
-		status $?
 		;;
 	stop )
 		do_stop
-		status $?
-		;;
-	force-stop )
-		do_force_stop
-		status $?
-		;;
-	reload )
-		do_reload
-		status $?
 		;;
 	restart )
 		do_restart
-		status $?
+		;;
+	reload )
+		do_reload
 		;;
 	status )
-		echo -n "$DESC is "
-		if running; then
-			echo "running"
-		else
-			echo "not running"
-		fi
+		do_status
+		;;
+	force-stop )
+		do_force_stop
+		;;
+	force-reload )
+		restart
 		;;
 	*)
-		echo "Usage: service $NAME {start|stop|restart|reload|status|force-stop}" >&2
+		log_daemon_msg "Usage: service $NAME {start|stop|restart|reload|status|force-stop|force-reload}" >&2
 		exit 1
 		;;
 esac
